allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = new File(rootProject.projectDir, '../build')

subprojects {
    project.buildDir = new File("${rootProject.buildDir}/${project.name}")
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
